version: 2.1

executors:
  java17:
    docker:
      - image: cimg/openjdk:17.0.11
    working_directory: ~/project

filter_ignore_main_branches: &filter_ignore_main_branches
  filters:
    branches:
      ignore:
        - dev
        - main
filter_only_branches: &filter_only_branches
  filters:
    branches:
      only:
        - /feature\/.*/
        - /bugfix\/.*/
        - /task\/.*/

steps:
  - &checkout_code
    checkout:
      path: $CIRCLE_PROJECT_REPONAME

commands:
  build:
    description: "Building the application"
    steps:
      - run:
          name: "Running build"
          command: |
            echo 'Step into repository project folder : ' $CIRCLE_PROJECT_REPONAME
            cd ./$CIRCLE_PROJECT_REPONAME
            ./gradlew build
  install_os_tools:
    description: "Installing OS tools"
    steps:
      - run:
          name: "Update linux repositories"
          command: apt update
      - run:
          name: "Install wget"
          command: apt -y install wget
      - run:
          name: "Install wkhtmltopdf"
          command: apt -y install wkhtmltopdf
  download_zap:
    description: "Download ZAP"
    steps:
      - run:
          name: "Download ZAP"
          command: |
           wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2_15_0_unix.sh
           tar -xvf ZAP_2.15.0_Linux.tar.gz
           cd ZAP_2.15.0
    run_zap:
      description: "Running ZAP"
      steps:
        - run:
            name: "Running ZAP and saving HTML report"
            command: |
             ./zap.sh -cmd -quickurl $DAST_TARGET_URL -quickprogress -quickout ../zap_report.html
    convert_report_to_pdf:
      description: "Convert zap report to pdf"
      steps:
        - run:
            name: "Convert zap report to pdf"
            command: |
              cd ..
              wkhtmltopdf zap_report.html zap_report.pdf

jobs:
  build:
    executor: java17
    steps:
      - *checkout_code
      - build
      - store_artifacts:
          path: data-batch/build/reports/spotbugs/main/spotbugs.html
      - store_artifacts:
          path: data-batch/build/reports/spotbugs/test/spotbugs.html
      - store_test_results:
          path: data-batch/build/test-results/test
  security:
    executor: java17
    steps:
      - install_os_tools
      - download_zap
      - run_zap
      - convert_report_to_pdf
      - store_artifacts:
          path: zap_report.pdf

workflows:
  version: 2
  build-and-check:
    jobs:
      - build:
        <<: *filter_ignore_main_branches
        <<: *filter_only_branches
#      - security:
#          requires:
#            - build

